### ISSUE TITLE
Create Finish to return another page

### ISSUE THREAD

**Issue by Eflay** [immadisairaj/gyro_maze#1]
Hello, 

Firstly, thanks a lot for your game. I have one question :

Is it possible to turn over a new page when we have reached the end of the maze ?

**Comment by immadisairaj** [comment]
Hello @Eflay. I am sorry, I missed the notification.

Currently the application is only in the beginning stage. So, there is only one maze to play with. But, once it is refined free, we can have something like levels or other mazes for free play?

If you have anything, please feel free to re open the issue. Also, I am open for any contributions.

Thank you.

**Comment by Eflay** [comment]
Hello,

Don't worry, we have successfully implemented the feature.

Let me know, if you want the code.

**Comment by immadisairaj** [comment]
> Don't worry, we have successfully implemented the feature.

Wow. That is great..


> Let me know, if you want the code.

Can you please open a PR for it? Thank you..

**Comment by Eflay** [comment]
Well, in ball.dart, we just need to add this condition :

if(other.type == EntryExit.exit){
//code
}

In the onCollision function, after the first condition :

if(other is Wall){
}

**Comment by immadisairaj** [comment]
Thank you..

Please don't forget to add this repository as source and tag me when sharing anywhere.. It would mean so much to me.. 🙂

**Comment by Eflay** [comment]
Yes for sure don't worry
